# Executive Summary

Bird Conservancy of the Rockies (Bird Conservancy), in conjunction with our partners, conducted the 18th consecutive year of landbird monitoring for the Integrated Monitoring in Bird Conservation Regions (IMBCR) program. IMBCR is based on a spatially balanced sampling design which provides inference to avian populations at various scales, from local management units to entire states or Bird Conservation Regions, facilitating conservation at local and national levels. The nested design also provides a consistent and flexible framework for understanding and comparing the status and annual changes of bird populations with local and regional context. Collaboration across organizations and spatial scales increases sample sizes and improves the accuracy and precision of population estimates. Analyzing the data collectively allows us to estimate detection probabilities for species that would otherwise have insufficient numbers of detections at local scales. For these reasons, the IMBCR program is well-positioned to address conservation and management needs for a wide range of stakeholders, encouraging an interdisciplinary approach to bird conservation that combines monitoring, research, and management.    

In 2025, the IMBCR program’s area of inference encompassed four entire states (Colorado, Montana, Utah, and Wyoming) and portions of 11 additional states (Arizona, California, Idaho, Kansas, Nebraska, Nevada, New Mexico, North Dakota, Oklahoma, South Dakota, and Texas). We surveyed across US Forest Service (USFS) Regions 1, 2, 3, and 4; all of the Badlands and Prairies Bird Conservation Region (BCR 17), and portions of nine other BCRs: Great Basin (9), Northern Rockies (10), Prairie Potholes (11), Sierra Nevada (15), Southern Rockies/Colorado Plateau (16), Shortgrass Prairie (18), Central Mixed Grass Prairie (19), Sonoran and Mojave Deserts (33), and Sierra Madre Occidental (34). 

Observers conducted 13,445 point counts within 1,193 sampling units between April 27  and July 21, 2024. They detected 165,395 individual birds representing 327 species. This report summarizes the results of the 2025 field season.   

The IMBCR program has now collected avian occurrence and density data throughout the western US for up to 18 years in some regions. These data enable the program to provide critical trend information on bird populations at local and regional scales, aiding management decisions and conservation efforts. We highlight a few examples of these trends for natural resource practitioners to monitor both priority species of concern and common species in decline by accessing data via the Rocky Mountain Avian Data Center.
